package no.srrlsm.speechsplit.core

// ============================================================================
// TRANSLATIONS
// Kept in plain Kotlin (instead of Android's strings.xml) so the language can be switched
// instantly inside the app, and so the same texts work on a future Windows or iPad version.
// ============================================================================
data class Strings(
    // Tabs
    val tabSpeeches: String,
    val tabSettings: String,
    // Library
    val libraryTitle: String,
    val importLabel: String,
    val noSpeeches: String,
    val edit: String,
    val export: String,
    val delete: String,
    val createNewSpeech: String,
    val importTitle: String,
    val importHint: String,
    val imported: String,
    val importFailed: String,
    val cancel: String,
    val deleteTitle: (String) -> String,
    val cannotBeUndone: String,
    val exportChooser: String,
    val summary: (Int, String) -> String,
    // Default names
    val defaultSpeechTitle: String,
    val defaultFirstSegment: String,
    val defaultNewSegment: String,
    val untitledSpeech: String,
    val importedSpeech: String,
    // Edit
    val editTitle: String,
    val back: String,
    val speechTitleLabel: String,
    val segmentLabel: (Int) -> String,
    val deleteSegment: String,
    val timeLabel: String,
    val moveUp: String,
    val moveDown: String,
    val addSegment: String,
    val saveAndReady: String,
    // Ready
    val readyToSpeak: String,
    val startTimer: String,
    val library: String,
    // Timer
    val stopTimer: String,
    val totalPlan: (String) -> String,
    val aheadBehind: String,
    val nowOf: (Int, Int) -> String,
    val target: String,
    val segmentRemaining: String,
    val segmentOvertime: String,
    val segmentElapsed: String,
    val elapsedShort: String,
    val remainingShort: String,
    val overShort: String,
    val adjustedIncBanked: String,
    val adjustedOver: String,
    val banked: String,
    val finished: String,
    val overPlan: (String) -> String,
    val underPlan: (String) -> String,
    val onTime: String,
    val upNext: String,
    val segments: String,
    val undoNext: String,
    val done: String,
    val pause: String,
    val resume: String,
    val finish: String,
    val next: String,
    val stopDialogTitle: String,
    val stopDialogText: String,
    val stop: String,
    val keepGoing: String,
    // Settings
    val settingsTitle: String,
    val sectionGeneral: String,
    val sectionTimer: String,
    val sectionAlerts: String,
    val language: String,
    val languageSystem: String,
    val keepScreenOnTitle: String,
    val keepScreenOnDesc: String,
    val clockModeTitle: String,
    val clockRemaining: String,
    val clockElapsed: String,
    val warningTitle: String,
    val warningDesc: String,
    val warningOff: String,
    val percent: (Int) -> String,
    val showAdjustedTitle: String,
    val showAdjustedDesc: String,
    val flashTitle: String,
    val flashDesc: String,
    val vibrateTitle: String,
    val vibrateDesc: String,
    val vibrateUnavailable: String,
    // Appearance
    val appearanceTitle: String,
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    // Celebration
    val celebrateTitle: String,
    val celebrateDesc: String,
    val celebrateOff: String,
    val celebrateExact: String,
    val withinSeconds: (Int) -> String,
    val perfectTiming: String,
    // Unsaved edits
    val discardTitle: String,
    val discardText: String,
    val discard: String,
    val keepEditing: String,
    // History
    val history: String,
    val historyTitle: String,
    val noHistory: String,
    val statRuns: String,
    val statOnTarget: String,
    val statAverage: (Int) -> String,
    val statBest: String,
    val trendTitle: String,
    val suggestionsTitle: String,
    val suggestionsNote: String,
    val suggestOver: (String, String) -> String,
    val suggestUnder: (String, String) -> String,
    val segmentAveragesTitle: String,
    val runsTitle: String,
    val clearHistory: String,
    val clearHistoryTitle: String,
    val deleteRun: String,
    val shareReport: String,
    val reportPlan: (String) -> String,
    val reportTotal: String,
    // Quick timer
    val quickTimer: String,
    val quickMinutesLabel: String,
    val quickTimerName: (Int) -> String,
    val start: String,
    // Do Not Disturb
    val dndTitle: String,
    val dndDesc: String,
    val dndPermissionTitle: String,
    val dndPermissionText: String,
    val openSettings: String,
    val dndMissing: String,
    // Watch
    val watchTitle: String,
    val watchDesc: String,
    val watchBlocked: String,
    val notifWarningTitle: (String) -> String,
    val notifWarningText: (String) -> String,
    val notifOverTitle: (String) -> String,
    val notifOverText: String,
    val channelWarning: String,
    val channelOver: String,
    // Lectern mode
    val lecternOn: String,
    val lecternOff: String,
    // Desktop
    val copiedToClipboard: String,
    val keyboardTitle: String,
    val keyboardDesc: String,
    // Version and updates
    val aboutTitle: String,
    val versionLabel: (String) -> String,
    val checkUpdates: String,
    val checking: String,
    val upToDate: String,
    val updateFailed: String,
    val updateAvailable: (String) -> String,
    val updateNow: String,
    val later: String,
    val whatsNew: String,
    val autoCheckTitle: String,
    val autoCheckDesc: String,
    val downloadingUpdate: String,
    val updateHintAndroid: String,
    val website: String,
    // Sorting and archive
    val sortTitle: String,
    val sortLastUsed: String,
    val sortCreated: String,
    val sortName: String,
    val moreOptions: String,
    val archiveAction: String,
    val archiveTitle: String,
    val archiveCount: (Int) -> String,
    val archiveEmpty: String,
    val archived: String,
    val restore: String,
    val restored: String,
    val deleteForeverText: String,
    val importFromFile: String,
    val importFromFileDesc: String,
    val importPaste: String,
    val importPasteDesc: String,
    val dropHint: String,
    val importReading: String,
    val importUnreadable: String,
    val importUnsupported: String,
    val importNothing: String,
    val suggestTitle: String,
    val suggestFromHeadings: String,
    val suggestEvenly: String,
    val suggestEditNote: String,
    val timesFrom: String,
    val timesFromPace: String,
    val timesFromTotal: String,
    val paceLabel: (Int) -> String,
    val partsTitle: String,
    val partsAuto: String,
    val partTitle: (Int) -> String,
    val wordsCount: (Int) -> String,
    val continueLabel: String,
    val patchNotes: String,
    val yourVersion: String,
    val notesLoading: String,
    val notesFailed: String,
    val noNotes: String,
    val viewOnGitHub: String,
    val feedback: String,
    val feedbackText: String,
    val feedbackBug: String,
    val feedbackIdea: String,
    val feedbackOther: String,
    val feedbackDescribe: String,
    val noEmailApp: (String) -> String,
    val privacy: String,
    val madeBy: String,
    val close: String,
    val paceNote: String,
)

val EnglishStrings = Strings(
    tabSpeeches = "Speeches",
    tabSettings = "Settings",
    libraryTitle = "Speech Library",
    importLabel = "Import",
    noSpeeches = "No speeches saved yet.",
    edit = "Edit",
    export = "Export",
    delete = "Delete",
    createNewSpeech = "Create New Speech",
    importTitle = "Import speech",
    importHint = "Paste an exported speech, or the text of your speech",
    imported = "Imported",
    importFailed = "That doesn't look like an exported speech",
    cancel = "Cancel",
    deleteTitle = { "Delete \"$it\"?" },
    cannotBeUndone = "This can't be undone.",
    exportChooser = "Export speech",
    summary = { n, t -> "$n segment${if (n == 1) "" else "s"} · $t total" },
    defaultSpeechTitle = "New Speech",
    defaultFirstSegment = "Introduction",
    defaultNewSegment = "New Segment",
    untitledSpeech = "Untitled speech",
    importedSpeech = "Imported speech",
    editTitle = "Edit Speech",
    back = "Back",
    speechTitleLabel = "Speech title",
    segmentLabel = { "Segment $it" },
    deleteSegment = "Delete segment",
    timeLabel = "Time (e.g. 4.30)",
    moveUp = "Move up",
    moveDown = "Move down",
    addSegment = "Add Segment",
    saveAndReady = "Save & Ready",
    readyToSpeak = "READY TO SPEAK",
    startTimer = "START TIMER",
    library = "Library",
    stopTimer = "Stop timer",
    totalPlan = { "TOTAL · PLAN $it" },
    aheadBehind = "AHEAD / BEHIND",
    nowOf = { i, n -> "NOW · $i OF $n" },
    target = "TARGET",
    segmentRemaining = "SEGMENT REMAINING",
    segmentOvertime = "SEGMENT OVERTIME",
    segmentElapsed = "SEGMENT ELAPSED",
    elapsedShort = "ELAPSED",
    remainingShort = "LEFT",
    overShort = "OVER",
    adjustedIncBanked = "ADJUSTED · INC. BANKED",
    adjustedOver = "ADJUSTED · OVER SCHEDULE",
    banked = "BANKED",
    finished = "FINISHED",
    overPlan = { "$it over plan" },
    underPlan = { "$it under plan" },
    onTime = "Exactly on time",
    upNext = "UP NEXT",
    segments = "SEGMENTS",
    undoNext = "Undo next",
    done = "DONE",
    pause = "PAUSE",
    resume = "RESUME",
    finish = "FINISH",
    next = "NEXT",
    stopDialogTitle = "Stop the timer?",
    stopDialogText = "The times from this run will be cleared.",
    stop = "Stop",
    keepGoing = "Keep going",
    settingsTitle = "Settings",
    sectionGeneral = "GENERAL",
    sectionTimer = "TIMER",
    sectionAlerts = "ALERTS",
    language = "Language",
    languageSystem = "System default",
    keepScreenOnTitle = "Keep screen on",
    keepScreenOnDesc = "Stops the screen from sleeping while the timer runs.",
    clockModeTitle = "Segment clock shows",
    clockRemaining = "Time left",
    clockElapsed = "Time spoken",
    warningTitle = "Warning before time is up",
    warningDesc = "Turns the clock yellow when this much of a segment is left.",
    warningOff = "Off",
    percent = { "$it%" },
    showAdjustedTitle = "Show adjusted time",
    showAdjustedDesc = "The box that includes time banked from earlier segments.",
    flashTitle = "Flash screen edge",
    flashDesc = "A coloured flash at the warning and when a segment runs out.",
    vibrateTitle = "Vibrate",
    vibrateDesc = "A short buzz at the warning, a longer one when time is up.",
    vibrateUnavailable = "This device can't vibrate.",
    appearanceTitle = "Appearance",
    themeSystem = "System",
    themeLight = "Light",
    themeDark = "Dark",
    celebrateTitle = "Celebrate perfect timing",
    celebrateDesc = "Confetti when your total time lands on the target.",
    celebrateOff = "Off",
    celebrateExact = "Exact",
    withinSeconds = { "±$it s" },
    perfectTiming = "Perfect timing!",
    discardTitle = "Discard changes?",
    discardText = "Your edits to this speech haven't been saved.",
    discard = "Discard",
    keepEditing = "Keep editing",
    history = "History",
    historyTitle = "Practice history",
    noHistory = "Finish a run of this speech and it shows up here.",
    statRuns = "Runs",
    statOnTarget = "On target",
    statAverage = { "Average (last $it)" },
    statBest = "Best",
    trendTitle = "LAST RUNS VS. PLAN",
    suggestionsTitle = "SUGGESTIONS",
    suggestionsNote = "Based on your latest runs. Your plan is not changed.",
    suggestOver = { avg, sug -> "You average $avg here. Plan $sug, or trim this part." },
    suggestUnder = { avg, sug -> "You average $avg here. Plan $sug, or add material." },
    segmentAveragesTitle = "AVERAGE PER SEGMENT",
    runsTitle = "RUNS",
    clearHistory = "Clear history",
    clearHistoryTitle = "Delete all runs of this speech?",
    deleteRun = "Delete run",
    shareReport = "Share report",
    reportPlan = { "plan $it" },
    reportTotal = "Total",
    quickTimer = "Quick timer",
    quickMinutesLabel = "Minutes",
    quickTimerName = { "Quick timer · $it min" },
    start = "Start",
    dndTitle = "Do Not Disturb while speaking",
    dndDesc = "Silences calls and notifications while the timer runs, then turns it off again.",
    dndPermissionTitle = "Allow Do Not Disturb",
    dndPermissionText = "Android needs your permission first. Find Speech Split in the list, allow access, then come back.",
    openSettings = "Open settings",
    dndMissing = "Do Not Disturb isn't allowed yet, so it stayed off.",
    watchTitle = "Buzz my smartwatch",
    watchDesc = "Sends a silent notification at the warning and when time is up, so a connected watch vibrates (Wear OS, Galaxy Watch and most watches that show phone notifications).",
    watchBlocked = "Notifications are blocked for Speech Split, so the watch can't be reached.",
    notifWarningTitle = { "$it: almost time" },
    notifWarningText = { "$it left" },
    notifOverTitle = { "$it: time's up" },
    notifOverText = "Move on when you're ready.",
    channelWarning = "Warning before time is up",
    channelOver = "Time is up",
    lecternOn = "Big clock",
    lecternOff = "Normal view",
    copiedToClipboard = "Copied. Paste it wherever you want to share it.",
    keyboardTitle = "KEYBOARD AND PRESENTATION CLICKER",
    keyboardDesc = "Space: pause or resume\n→, Page Down or Enter: next\n←, Page Up or Backspace: undo next\nF: big clock",
    aboutTitle = "ABOUT",
    versionLabel = { "Version $it" },
    checkUpdates = "Check for updates",
    checking = "Checking…",
    upToDate = "You have the latest version.",
    updateFailed = "Couldn't check right now. Are you online?",
    updateAvailable = { "Version $it is available" },
    updateNow = "Update now",
    later = "Later",
    whatsNew = "What's new",
    autoCheckTitle = "Check for updates automatically",
    autoCheckDesc = "Asks GitHub for a newer version when the app starts. Nothing else is sent.",
    downloadingUpdate = "Downloading the update. The installer opens by itself.",
    updateHintAndroid = "The new version downloads in your browser. Open it when it's done to install.",
    website = "Website",
    sortTitle = "Sort by",
    sortLastUsed = "Last used",
    sortCreated = "Newest",
    sortName = "Name",
    moreOptions = "More options",
    archiveAction = "Archive",
    archiveTitle = "Archive",
    archiveCount = { "Archive ($it)" },
    archiveEmpty = "Nothing here yet. Archived speeches keep their practice history and can be restored at any time.",
    archived = "Moved to the archive",
    restore = "Restore",
    restored = "Restored",
    deleteForeverText = "The speech and its practice history are deleted for good. Tip: archive it instead to keep it.",
    importFromFile = "Open a document",
    importFromFileDesc = "PDF, Word (.docx), OpenDocument or text. Segments are suggested from the text.",
    importPaste = "Paste text",
    importPasteDesc = "An exported speech, or the text of your speech.",
    dropHint = "Tip: you can also drag a document onto the app.",
    importReading = "Reading the document…",
    importUnreadable = "No text found in that file. Scanned PDFs (pictures of text) can't be read.",
    importUnsupported = "That file type isn't supported. Try PDF, Word (.docx), OpenDocument (.odt) or text.",
    importNothing = "There's no text to split. Paste the text of your speech, or an exported speech.",
    suggestTitle = "Suggested segments",
    suggestFromHeadings = "Split at the headings in your document.",
    suggestEvenly = "No headings found, so the text is split into parts of about equal length.",
    suggestEditNote = "Nothing is saved yet. You can change names and times on the next screen.",
    timesFrom = "Times from",
    timesFromPace = "Speaking pace",
    timesFromTotal = "Total time",
    paceLabel = { when (it) { 110 -> "Calm"; 150 -> "Brisk"; else -> "Normal" } + " $it" },
    partsTitle = "Number of parts",
    partsAuto = "Auto",
    partTitle = { "Part $it" },
    wordsCount = { "$it words" },
    continueLabel = "Continue",
    patchNotes = "Patch notes",
    yourVersion = "your version",
    notesLoading = "Loading from GitHub…",
    notesFailed = "Couldn't load the patch notes. Are you online?",
    noNotes = "No notes for this version.",
    viewOnGitHub = "View on GitHub",
    feedback = "Send feedback",
    feedbackText = "Found a bug, or have an idea for something better? Pick one, and your email app opens with a short template.",
    feedbackBug = "Report a bug",
    feedbackIdea = "Suggest an improvement",
    feedbackOther = "Something else",
    feedbackDescribe = "Describe it here (for a bug: what you did, and what happened):",
    noEmailApp = { "No email app found. Write to $it" },
    privacy = "Privacy",
    madeBy = "Made by Dylan Scott Meschner",
    close = "Close",
    paceNote = "Words per minute. Most people speak about 130 in a talk.",
)

val GermanStrings = Strings(
    tabSpeeches = "Reden",
    tabSettings = "Einstellungen",
    libraryTitle = "Meine Reden",
    importLabel = "Importieren",
    noSpeeches = "Noch keine Reden gespeichert.",
    edit = "Bearbeiten",
    export = "Exportieren",
    delete = "Löschen",
    createNewSpeech = "Neue Rede erstellen",
    importTitle = "Rede importieren",
    importHint = "Exportierte Rede oder den Text deiner Rede einfügen",
    imported = "Importiert",
    importFailed = "Das sieht nicht nach einer exportierten Rede aus",
    cancel = "Abbrechen",
    deleteTitle = { "„$it“ löschen?" },
    cannotBeUndone = "Das kann nicht rückgängig gemacht werden.",
    exportChooser = "Rede exportieren",
    summary = { n, t -> "$n ${if (n == 1) "Abschnitt" else "Abschnitte"} · $t gesamt" },
    defaultSpeechTitle = "Neue Rede",
    defaultFirstSegment = "Einleitung",
    defaultNewSegment = "Neuer Abschnitt",
    untitledSpeech = "Unbenannte Rede",
    importedSpeech = "Importierte Rede",
    editTitle = "Rede bearbeiten",
    back = "Zurück",
    speechTitleLabel = "Titel der Rede",
    segmentLabel = { "Abschnitt $it" },
    deleteSegment = "Abschnitt löschen",
    timeLabel = "Zeit (z. B. 4.30)",
    moveUp = "Nach oben",
    moveDown = "Nach unten",
    addSegment = "Abschnitt hinzufügen",
    saveAndReady = "Speichern & los",
    readyToSpeak = "BEREIT",
    startTimer = "TIMER STARTEN",
    library = "Übersicht",
    stopTimer = "Timer stoppen",
    totalPlan = { "GESAMT · PLAN $it" },
    aheadBehind = "VOR / HINTER PLAN",
    nowOf = { i, n -> "JETZT · $i VON $n" },
    target = "ZIEL",
    segmentRemaining = "RESTZEIT",
    segmentOvertime = "ÜBERZEIT",
    segmentElapsed = "VERSTRICHEN",
    elapsedShort = "VERSTRICHEN",
    remainingShort = "REST",
    overShort = "ÜBER",
    adjustedIncBanked = "ANGEPASST · INKL. PUFFER",
    adjustedOver = "ANGEPASST · ÜBER PLAN",
    banked = "PUFFER",
    finished = "FERTIG",
    overPlan = { "$it über Plan" },
    underPlan = { "$it unter Plan" },
    onTime = "Genau im Plan",
    upNext = "ALS NÄCHSTES",
    segments = "ABSCHNITTE",
    undoNext = "Weiter rückgängig machen",
    done = "FERTIG",
    pause = "PAUSE",
    resume = "WEITER",
    finish = "ENDE",
    next = "NÄCHSTER",
    stopDialogTitle = "Timer stoppen?",
    stopDialogText = "Die Zeiten dieses Durchlaufs werden gelöscht.",
    stop = "Stoppen",
    keepGoing = "Weitermachen",
    settingsTitle = "Einstellungen",
    sectionGeneral = "ALLGEMEIN",
    sectionTimer = "TIMER",
    sectionAlerts = "HINWEISE",
    language = "Sprache",
    languageSystem = "Systemsprache",
    keepScreenOnTitle = "Bildschirm anlassen",
    keepScreenOnDesc = "Verhindert, dass der Bildschirm ausgeht, während der Timer läuft.",
    clockModeTitle = "Abschnittsuhr zeigt",
    clockRemaining = "Restzeit",
    clockElapsed = "Gesprochene Zeit",
    warningTitle = "Warnung vor Zeitende",
    warningDesc = "Die Uhr wird gelb, wenn noch so viel vom Abschnitt übrig ist.",
    warningOff = "Aus",
    percent = { "$it %" },
    showAdjustedTitle = "Angepasste Zeit anzeigen",
    showAdjustedDesc = "Die Box, die den Puffer aus früheren Abschnitten einrechnet.",
    flashTitle = "Bildschirmrand aufblinken",
    flashDesc = "Farbiges Aufblinken bei der Warnung und wenn die Zeit abläuft.",
    vibrateTitle = "Vibrieren",
    vibrateDesc = "Kurz bei der Warnung, länger wenn die Zeit um ist.",
    vibrateUnavailable = "Dieses Gerät kann nicht vibrieren.",
    appearanceTitle = "Darstellung",
    themeSystem = "System",
    themeLight = "Hell",
    themeDark = "Dunkel",
    celebrateTitle = "Perfektes Timing feiern",
    celebrateDesc = "Konfetti, wenn deine Gesamtzeit genau das Ziel trifft.",
    celebrateOff = "Aus",
    celebrateExact = "Exakt",
    withinSeconds = { "±$it s" },
    perfectTiming = "Perfektes Timing!",
    discardTitle = "Änderungen verwerfen?",
    discardText = "Deine Änderungen an dieser Rede wurden nicht gespeichert.",
    discard = "Verwerfen",
    keepEditing = "Weiter bearbeiten",
    history = "Verlauf",
    historyTitle = "Übungsverlauf",
    noHistory = "Schließe einen Durchlauf dieser Rede ab, dann erscheint er hier.",
    statRuns = "Durchläufe",
    statOnTarget = "Im Ziel",
    statAverage = { "Schnitt (letzte $it)" },
    statBest = "Bester",
    trendTitle = "LETZTE DURCHLÄUFE VS. PLAN",
    suggestionsTitle = "VORSCHLÄGE",
    suggestionsNote = "Basierend auf deinen letzten Durchläufen. Dein Plan wird nicht geändert.",
    suggestOver = { avg, sug -> "Hier liegst du im Schnitt bei $avg. Plane $sug ein oder kürze diesen Teil." },
    suggestUnder = { avg, sug -> "Hier liegst du im Schnitt bei $avg. Plane $sug ein oder ergänze Inhalt." },
    segmentAveragesTitle = "SCHNITT PRO ABSCHNITT",
    runsTitle = "DURCHLÄUFE",
    clearHistory = "Verlauf löschen",
    clearHistoryTitle = "Alle Durchläufe dieser Rede löschen?",
    deleteRun = "Durchlauf löschen",
    shareReport = "Bericht teilen",
    reportPlan = { "Plan $it" },
    reportTotal = "Gesamt",
    quickTimer = "Schnell-Timer",
    quickMinutesLabel = "Minuten",
    quickTimerName = { "Schnell-Timer · $it Min." },
    start = "Starten",
    dndTitle = "„Nicht stören“ während der Rede",
    dndDesc = "Schaltet Anrufe und Benachrichtigungen stumm, solange der Timer läuft, und danach wieder zurück.",
    dndPermissionTitle = "„Nicht stören“ erlauben",
    dndPermissionText = "Android braucht zuerst deine Erlaubnis. Suche Speech Split in der Liste, erlaube den Zugriff und komm zurück.",
    openSettings = "Einstellungen öffnen",
    dndMissing = "„Nicht stören“ ist noch nicht erlaubt und blieb deshalb aus.",
    watchTitle = "Smartwatch vibrieren lassen",
    watchDesc = "Sendet eine lautlose Benachrichtigung bei der Warnung und wenn die Zeit um ist, damit eine verbundene Uhr vibriert (Wear OS, Galaxy Watch und die meisten Uhren, die Handy-Benachrichtigungen anzeigen).",
    watchBlocked = "Benachrichtigungen sind für Speech Split blockiert, die Uhr ist so nicht erreichbar.",
    notifWarningTitle = { "$it: gleich vorbei" },
    notifWarningText = { "noch $it" },
    notifOverTitle = { "$it: Zeit ist um" },
    notifOverText = "Weiter, wenn du so weit bist.",
    channelWarning = "Warnung vor Zeitende",
    channelOver = "Zeit ist um",
    lecternOn = "Große Uhr",
    lecternOff = "Normale Ansicht",
    copiedToClipboard = "Kopiert. Füge es dort ein, wo du es teilen möchtest.",
    keyboardTitle = "TASTATUR UND PRÄSENTER",
    keyboardDesc = "Leertaste: Pause oder weiter\n→, Bild ab oder Enter: nächster\n←, Bild auf oder Rücktaste: rückgängig\nF: große Uhr",
    aboutTitle = "ÜBER DIE APP",
    versionLabel = { "Version $it" },
    checkUpdates = "Nach Updates suchen",
    checking = "Wird geprüft …",
    upToDate = "Du hast die neueste Version.",
    updateFailed = "Konnte gerade nicht prüfen. Bist du online?",
    updateAvailable = { "Version $it ist verfügbar" },
    updateNow = "Jetzt aktualisieren",
    later = "Später",
    whatsNew = "Neu in dieser Version",
    autoCheckTitle = "Automatisch nach Updates suchen",
    autoCheckDesc = "Fragt beim Start bei GitHub nach einer neueren Version. Sonst wird nichts gesendet.",
    downloadingUpdate = "Das Update wird geladen. Der Installer öffnet sich von selbst.",
    updateHintAndroid = "Die neue Version wird im Browser geladen. Öffne sie danach, um sie zu installieren.",
    website = "Webseite",
    sortTitle = "Sortieren nach",
    sortLastUsed = "Zuletzt benutzt",
    sortCreated = "Neueste",
    sortName = "Name",
    moreOptions = "Weitere Optionen",
    archiveAction = "Archivieren",
    archiveTitle = "Archiv",
    archiveCount = { "Archiv ($it)" },
    archiveEmpty = "Noch nichts hier. Archivierte Reden behalten ihren Übungsverlauf und können jederzeit wiederhergestellt werden.",
    archived = "Ins Archiv verschoben",
    restore = "Wiederherstellen",
    restored = "Wiederhergestellt",
    deleteForeverText = "Die Rede und ihr Übungsverlauf werden endgültig gelöscht. Tipp: Archiviere sie stattdessen, um sie zu behalten.",
    importFromFile = "Dokument öffnen",
    importFromFileDesc = "PDF, Word (.docx), OpenDocument oder Text. Abschnitte werden aus dem Text vorgeschlagen.",
    importPaste = "Text einfügen",
    importPasteDesc = "Eine exportierte Rede oder den Text deiner Rede.",
    dropHint = "Tipp: Du kannst ein Dokument auch einfach auf die App ziehen.",
    importReading = "Dokument wird gelesen…",
    importUnreadable = "Keinen Text in der Datei gefunden. Gescannte PDFs (Bilder von Text) können nicht gelesen werden.",
    importUnsupported = "Dieser Dateityp wird nicht unterstützt. Versuche PDF, Word (.docx), OpenDocument (.odt) oder Text.",
    importNothing = "Kein Text zum Aufteilen. Füge den Text deiner Rede oder eine exportierte Rede ein.",
    suggestTitle = "Vorgeschlagene Abschnitte",
    suggestFromHeadings = "Aufgeteilt an den Überschriften deines Dokuments.",
    suggestEvenly = "Keine Überschriften gefunden, daher ist der Text in etwa gleich lange Teile aufgeteilt.",
    suggestEditNote = "Noch ist nichts gespeichert. Namen und Zeiten kannst du im nächsten Schritt ändern.",
    timesFrom = "Zeiten nach",
    timesFromPace = "Sprechtempo",
    timesFromTotal = "Gesamtzeit",
    paceLabel = { when (it) { 110 -> "Ruhig"; 150 -> "Zügig"; else -> "Normal" } + " $it" },
    partsTitle = "Anzahl Teile",
    partsAuto = "Auto",
    partTitle = { "Teil $it" },
    wordsCount = { "$it Wörter" },
    continueLabel = "Weiter",
    patchNotes = "Versionshinweise",
    yourVersion = "deine Version",
    notesLoading = "Wird von GitHub geladen…",
    notesFailed = "Versionshinweise konnten nicht geladen werden. Bist du online?",
    noNotes = "Keine Hinweise zu dieser Version.",
    viewOnGitHub = "Auf GitHub ansehen",
    feedback = "Feedback senden",
    feedbackText = "Einen Fehler gefunden oder eine Idee? Wähle aus, dann öffnet sich deine E-Mail-App mit einer kurzen Vorlage.",
    feedbackBug = "Fehler melden",
    feedbackIdea = "Verbesserung vorschlagen",
    feedbackOther = "Etwas anderes",
    feedbackDescribe = "Beschreibe es hier (bei einem Fehler: was du gemacht hast und was passiert ist):",
    noEmailApp = { "Keine E-Mail-App gefunden. Schreib an $it" },
    privacy = "Datenschutz",
    madeBy = "Gemacht von Dylan Scott Meschner",
    close = "Schließen",
    paceNote = "Wörter pro Minute. In einer Rede spricht man meist etwa 130.",
)

val NorwegianStrings = Strings(
    tabSpeeches = "Taler",
    tabSettings = "Innstillinger",
    libraryTitle = "Mine taler",
    importLabel = "Importer",
    noSpeeches = "Ingen taler lagret ennå.",
    edit = "Rediger",
    export = "Eksporter",
    delete = "Slett",
    createNewSpeech = "Lag ny tale",
    importTitle = "Importer tale",
    importHint = "Lim inn en eksportert tale, eller teksten til talen",
    imported = "Importert",
    importFailed = "Dette ser ikke ut som en eksportert tale",
    cancel = "Avbryt",
    deleteTitle = { "Slette «$it»?" },
    cannotBeUndone = "Dette kan ikke angres.",
    exportChooser = "Eksporter tale",
    summary = { n, t -> "$n ${if (n == 1) "del" else "deler"} · $t totalt" },
    defaultSpeechTitle = "Ny tale",
    defaultFirstSegment = "Innledning",
    defaultNewSegment = "Ny del",
    untitledSpeech = "Tale uten navn",
    importedSpeech = "Importert tale",
    editTitle = "Rediger tale",
    back = "Tilbake",
    speechTitleLabel = "Tittel på talen",
    segmentLabel = { "Del $it" },
    deleteSegment = "Slett del",
    timeLabel = "Tid (f.eks. 4.30)",
    moveUp = "Flytt opp",
    moveDown = "Flytt ned",
    addSegment = "Legg til del",
    saveAndReady = "Lagre og gjør klar",
    readyToSpeak = "KLAR",
    startTimer = "START TIMEREN",
    library = "Oversikt",
    stopTimer = "Stopp timeren",
    totalPlan = { "TOTALT · PLAN $it" },
    aheadBehind = "FORAN / BAK",
    nowOf = { i, n -> "NÅ · $i AV $n" },
    target = "MÅL",
    segmentRemaining = "GJENSTÅR",
    segmentOvertime = "OVERTID",
    segmentElapsed = "BRUKT",
    elapsedShort = "BRUKT",
    remainingShort = "IGJEN",
    overShort = "OVER",
    adjustedIncBanked = "JUSTERT · INKL. BUFFER",
    adjustedOver = "JUSTERT · OVER PLANEN",
    banked = "BUFFER",
    finished = "FERDIG",
    overPlan = { "$it over planen" },
    underPlan = { "$it under planen" },
    onTime = "Akkurat på tiden",
    upNext = "NESTE",
    segments = "DELER",
    undoNext = "Angre neste",
    done = "FERDIG",
    pause = "PAUSE",
    resume = "FORTSETT",
    finish = "AVSLUTT",
    next = "NESTE",
    stopDialogTitle = "Stoppe timeren?",
    stopDialogText = "Tidene fra denne runden blir slettet.",
    stop = "Stopp",
    keepGoing = "Fortsett",
    settingsTitle = "Innstillinger",
    sectionGeneral = "GENERELT",
    sectionTimer = "TIMER",
    sectionAlerts = "VARSLER",
    language = "Språk",
    languageSystem = "Systemspråk",
    keepScreenOnTitle = "Hold skjermen på",
    keepScreenOnDesc = "Hindrer at skjermen slukker mens timeren går.",
    clockModeTitle = "Klokka for delen viser",
    clockRemaining = "Tid igjen",
    clockElapsed = "Tid brukt",
    warningTitle = "Varsel før tiden er ute",
    warningDesc = "Klokka blir gul når så mye av delen er igjen.",
    warningOff = "Av",
    percent = { "$it %" },
    showAdjustedTitle = "Vis justert tid",
    showAdjustedDesc = "Boksen som regner med bufferen fra tidligere deler.",
    flashTitle = "Blink i skjermkanten",
    flashDesc = "Et farget blink ved varselet og når tiden for en del er ute.",
    vibrateTitle = "Vibrer",
    vibrateDesc = "Kort ved varselet, lengre når tiden er ute.",
    vibrateUnavailable = "Denne enheten kan ikke vibrere.",
    appearanceTitle = "Utseende",
    themeSystem = "System",
    themeLight = "Lys",
    themeDark = "Mørk",
    celebrateTitle = "Feire perfekt timing",
    celebrateDesc = "Konfetti når totaltiden treffer målet ditt.",
    celebrateOff = "Av",
    celebrateExact = "Nøyaktig",
    withinSeconds = { "±$it s" },
    perfectTiming = "Perfekt timing!",
    discardTitle = "Forkaste endringene?",
    discardText = "Endringene i denne talen er ikke lagret.",
    discard = "Forkast",
    keepEditing = "Fortsett å redigere",
    history = "Historikk",
    historyTitle = "Øvingshistorikk",
    noHistory = "Fullfør en gjennomkjøring av talen, så dukker den opp her.",
    statRuns = "Runder",
    statOnTarget = "På målet",
    statAverage = { "Snitt (siste $it)" },
    statBest = "Beste",
    trendTitle = "SISTE RUNDER MOT PLANEN",
    suggestionsTitle = "FORSLAG",
    suggestionsNote = "Basert på de siste rundene dine. Planen din blir ikke endret.",
    suggestOver = { avg, sug -> "Her ligger du i snitt på $avg. Sett av $sug, eller kort ned denne delen." },
    suggestUnder = { avg, sug -> "Her ligger du i snitt på $avg. Sett av $sug, eller legg til mer stoff." },
    segmentAveragesTitle = "SNITT PER DEL",
    runsTitle = "RUNDER",
    clearHistory = "Slett historikk",
    clearHistoryTitle = "Slette alle rundene for denne talen?",
    deleteRun = "Slett runde",
    shareReport = "Del rapport",
    reportPlan = { "plan $it" },
    reportTotal = "Totalt",
    quickTimer = "Hurtigtimer",
    quickMinutesLabel = "Minutter",
    quickTimerName = { "Hurtigtimer · $it min" },
    start = "Start",
    dndTitle = "Ikke forstyrr mens du taler",
    dndDesc = "Demper anrop og varsler mens timeren går, og skrur det av igjen etterpå.",
    dndPermissionTitle = "Tillat «Ikke forstyrr»",
    dndPermissionText = "Android trenger tillatelse først. Finn Speech Split i lista, gi tilgang og kom tilbake hit.",
    openSettings = "Åpne innstillinger",
    dndMissing = "«Ikke forstyrr» er ikke tillatt ennå, så det ble ikke skrudd på.",
    watchTitle = "Vibrer smartklokka",
    watchDesc = "Sender et lydløst varsel ved varselet og når tiden er ute, så en tilkoblet klokke vibrerer (Wear OS, Galaxy Watch og de fleste klokker som viser varsler fra telefonen).",
    watchBlocked = "Varsler er blokkert for Speech Split, så klokka kan ikke nås.",
    notifWarningTitle = { "$it: snart tid" },
    notifWarningText = { "$it igjen" },
    notifOverTitle = { "$it: tiden er ute" },
    notifOverText = "Gå videre når du er klar.",
    channelWarning = "Varsel før tiden er ute",
    channelOver = "Tiden er ute",
    lecternOn = "Stor klokke",
    lecternOff = "Vanlig visning",
    copiedToClipboard = "Kopiert. Lim det inn der du vil dele det.",
    keyboardTitle = "TASTATUR OG PRESENTASJONSKLIKKER",
    keyboardDesc = "Mellomrom: pause eller fortsett\n→, Page Down eller Enter: neste\n←, Page Up eller Backspace: angre neste\nF: stor klokke",
    aboutTitle = "OM APPEN",
    versionLabel = { "Versjon $it" },
    checkUpdates = "Se etter oppdateringer",
    checking = "Sjekker …",
    upToDate = "Du har nyeste versjon.",
    updateFailed = "Fikk ikke sjekket nå. Er du på nett?",
    updateAvailable = { "Versjon $it er tilgjengelig" },
    updateNow = "Oppdater nå",
    later = "Senere",
    whatsNew = "Nytt i denne versjonen",
    autoCheckTitle = "Se etter oppdateringer automatisk",
    autoCheckDesc = "Spør GitHub om en nyere versjon når appen starter. Ingenting annet sendes.",
    downloadingUpdate = "Laster ned oppdateringen. Installasjonen åpner seg av seg selv.",
    updateHintAndroid = "Den nye versjonen lastes ned i nettleseren. Åpne den når den er ferdig for å installere.",
    website = "Nettside",
    sortTitle = "Sorter etter",
    sortLastUsed = "Sist brukt",
    sortCreated = "Nyeste",
    sortName = "Navn",
    moreOptions = "Flere valg",
    archiveAction = "Arkiver",
    archiveTitle = "Arkiv",
    archiveCount = { "Arkiv ($it)" },
    archiveEmpty = "Ingenting her ennå. Arkiverte taler beholder øvingshistorikken og kan gjenopprettes når som helst.",
    archived = "Flyttet til arkivet",
    restore = "Gjenopprett",
    restored = "Gjenopprettet",
    deleteForeverText = "Talen og øvingshistorikken slettes for godt. Tips: arkiver den heller hvis du vil beholde den.",
    importFromFile = "Åpne et dokument",
    importFromFileDesc = "PDF, Word (.docx), OpenDocument eller tekst. Segmenter foreslås ut fra teksten.",
    importPaste = "Lim inn tekst",
    importPasteDesc = "En eksportert tale, eller selve teksten til talen.",
    dropHint = "Tips: du kan også dra et dokument rett inn i appen.",
    importReading = "Leser dokumentet…",
    importUnreadable = "Fant ingen tekst i filen. Skannede PDF-er (bilder av tekst) kan ikke leses.",
    importUnsupported = "Den filtypen støttes ikke. Prøv PDF, Word (.docx), OpenDocument (.odt) eller tekst.",
    importNothing = "Ingen tekst å dele opp. Lim inn teksten til talen, eller en eksportert tale.",
    suggestTitle = "Foreslåtte segmenter",
    suggestFromHeadings = "Delt opp ved overskriftene i dokumentet.",
    suggestEvenly = "Fant ingen overskrifter, så teksten er delt i omtrent like lange deler.",
    suggestEditNote = "Ingenting er lagret ennå. Du kan endre navn og tider på neste skjerm.",
    timesFrom = "Tider ut fra",
    timesFromPace = "Taletempo",
    timesFromTotal = "Total tid",
    paceLabel = { when (it) { 110 -> "Rolig"; 150 -> "Raskt"; else -> "Normalt" } + " $it" },
    partsTitle = "Antall deler",
    partsAuto = "Auto",
    partTitle = { "Del $it" },
    wordsCount = { "$it ord" },
    continueLabel = "Fortsett",
    patchNotes = "Patch notes",
    yourVersion = "din versjon",
    notesLoading = "Henter fra GitHub…",
    notesFailed = "Fikk ikke hentet patch notes. Er du på nett?",
    noNotes = "Ingen notater for denne versjonen.",
    viewOnGitHub = "Se på GitHub",
    feedback = "Send tilbakemelding",
    feedbackText = "Funnet en feil, eller har du en idé? Velg en av dem, så åpnes e-postappen med en kort mal.",
    feedbackBug = "Meld en feil",
    feedbackIdea = "Foreslå en forbedring",
    feedbackOther = "Noe annet",
    feedbackDescribe = "Beskriv det her (ved en feil: hva du gjorde, og hva som skjedde):",
    noEmailApp = { "Fant ingen e-postapp. Skriv til $it" },
    privacy = "Personvern",
    madeBy = "Laget av Dylan Scott Meschner",
    close = "Lukk",
    paceNote = "Ord per minutt. De fleste snakker rundt 130 i en tale.",
)

/** "System default" picks German or Norwegian if the device uses it, otherwise English. */
fun AppLanguage.resolve(systemLanguage: String): AppLanguage = if (this != AppLanguage.SYSTEM) this else
    when (systemLanguage) {
        "de" -> AppLanguage.GERMAN
        "nb", "no", "nn" -> AppLanguage.NORWEGIAN
        else -> AppLanguage.ENGLISH
    }

fun stringsFor(language: AppLanguage, systemLanguage: String): Strings = when (language.resolve(systemLanguage)) {
    AppLanguage.GERMAN -> GermanStrings
    AppLanguage.NORWEGIAN -> NorwegianStrings
    else -> EnglishStrings
}

/** Language names are always shown in their own language, so anyone can find theirs. */
fun languageName(language: AppLanguage, s: Strings): String = when (language) {
    AppLanguage.SYSTEM -> s.languageSystem
    AppLanguage.ENGLISH -> "English"
    AppLanguage.GERMAN -> "Deutsch"
    AppLanguage.NORWEGIAN -> "Norsk"
}

